<a href="https://colab.research.google.com/github/luiz-star/Arrays_Funcoes_Aritmeticas/blob/main/Arrays_Funcoes_Aritmeticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Funções aritméticas: soma, subtração e divisão

In [3]:
# importando a biblioteca
import numpy as np

In [5]:
#criação de dois arrays x e y
x = np.ones((2, 2))
y = np.eye(2)
print('x: \n', x)
print('y: \n', y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [6]:
# soma
print('soma de dois arrays:\n', x + y)
print('soma com float/int:\n', x + 2)  # broadcasting (transmissão)

soma de dois arrays:
 [[2. 1.]
 [1. 2.]]
soma com float/int:
 [[3. 3.]
 [3. 3.]]


In [9]:
# subtração
print('subtração de dois arrays:\n', x - y)
print('subtração com float/int:\n', x - 2) #broadcasting

subtração de dois arrays:
 [[0. 1.]
 [1. 0.]]
subtração com float/int:
 [[-1. -1.]
 [-1. -1.]]


In [8]:
# divisão
print('divisão de dois arrays:\n', x / y)
print('divisão com float/int:\n', x / 2)# broadcasting

divisão de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisão com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [ ]:
# Quando o brodcasting não funciona
# np.array([1, 2, 3]) + np.array([1, 2])

In [10]:
# soma, subtração e divisão
print('combinação de operações: \n', (x+y)/(x-2))

combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]


# Multiplicação

In [11]:
# multiplicação elemento a elemento
print('x: \n', x)
print('y: \n', y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [12]:
# Multiplicação
print('multiplicação matricial (np.dot) :\n', x * y)
print('multiplicação com float/int:\n', x * 2)# broadcasting

multiplicação matricial (np.dot) :
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int:
 [[2. 2.]
 [2. 2.]]


In [14]:
# Multiplicação Matricial
print('multiplicação matricial (np.dot):\n', np.dot(x, y))
print('multiplicação matricial (@):\n', x @ y)
print('multiplicação matricial (.dot):\n', x.dot(y))

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot):
 [[1. 1.]
 [1. 1.]]


In [16]:
"""
Exemplo:
Solução de um sistema de equações:
  a + 2*b =7
  3*a -2*b = -11
  solução análitica: (a, b) = (-1, 4)
Matricialmente, este problema tem a seguinte forma:
  Ax = c, onde:
  - x = [a, b]
  - A = [[1, 2], [-3, -2]]
  - c = [7, -11]
  solução numérica: x = inv(A) @ c,
"""

# Definição do problema
A = np.array([[1, 2], [3, -2]])
c = np.array([[7], [-11]])
print('A: \n', A)
print('c: \n', c)

A: 
 [[ 1  2]
 [ 3 -2]]
c: 
 [[  7]
 [-11]]


# Comparações (São operações elemento a elemento)

In [19]:
# solução
x = np.dot(np.linalg.inv(A), c)# A inversa da matriz
#x = np.linalg.inv(A) @ c
print('(a, b):', x.ravel())           

(a, b): [-1.  4.]


In [20]:
# Criação dos arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([1.5, 3.5])
print('x: \n', x)
print('y:\n', y)

x: 
 [[1 2]
 [3 4]]
y:
 [1.5 3.5]


Indexação Booleana : Filtro

In [21]:
# comparações ponto a ponto

print('Comparação de um array com um escalar (>): \n', x > 2)
print('Comparação de um array com um escalar (>=): \n', x >=2)
print('Comparação de um array com um escalar (<): \n', x < 2)
print('Comparação de um array com um escalar (<=): \n', x <=2)
print('Comparação entre arrays (==): \n', x == x)
print('Comparação entre arrays (>): \n', x > x)
print('Comparação entre arrays (>): \n', x > y)# broadcasting

Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [False False]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]]


In [25]:
# indexação booleana
x = np.array([[1, 3, 7],
             [4, 11, 21],
             [42, 8, 9]])
print('x:\n', x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [26]:
# indexação booleana: retornar o número de elementos
#Maiores que K
k = 10
cond = x > k
print('condição: \n', cond)
print(f'elementos maiores que {k}:', x[cond])
print(f'número de elementos maiores que {k}:', len(x[cond]))

condição: 
 [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10: [11 21 42]
número de elementos maiores que 10: 3


In [27]:
# Indexação booleana: extração ds números pares
cond = x % 2 == 0  #números pares
print('condição: \n', cond)
print('números pares:', x[cond])

condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
números pares: [ 4 42  8]


In [28]:
# Indexação booleana: Extração dos números impares
cond = x % 2 == 1 # números pares
print('condição: \n', cond)
print('números pares:', x[cond])

condição: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
números pares: [ 1  3  7 11 21  9]
